[rule]
author = ["NVB"]
description = "Looks for .zip files being created in a file path containing Windows\\Temp"
from = "now-9m" # default, change as needed
#index = ["logs-endpoint.events.process*"]
language = "eql"
#license = "Elastic License v2"
name = "Data Archive for Exfil (via Git)"
#note = "Note"
#references = [
#    "https://github.com/center-for-threat-informed-defense/adversary_emulation_library/blob/master/apt29/Archive/CALDERA_DIY/evals/payloads/stepSeventeen_email.ps1",
#]
risk_score = 25
rule_id = "00000000-0000-0000-0000-000000000002"
severity = "medium"

type = "query"

query = '''
    event.dataset : "endpoint.events.file" and event.action: (creation or overwrite) and process.name : "powershell.exe" and file.path: *Windows\\Temp\\* and file.name: *.zip
'''


[[rule.threat]] # Example Tactic, Technique, Sub-Technique
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1074" #T id
name = "Data Staged"
reference = "https://attack.mitre.org/techniques/T1074/"
# Subtechnique if present:
[[rule.threat.technique.subtechnique]]
id = "T1074.001"
name = "Local Data Staging"
reference = "https://attack.mitre.org/techniques/T1074/001/"

[rule.threat.tactic]
id = "TA0009" # TA id
name = "Collection"
reference = "https://attack.mitre.org/tactics/TA0009/"

# Optional Fields: 
# throttle: 7d
# version: 1
# interval: 5m

# [rule.threshold]
# field = ["host.hostname"]
# value = 100
