# This is a basic workflow to help you get started with Actions

name: All Detections To Elastic

# Controls when the workflow will run
on:
  # Only run this when you set up a new Elastic Version
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  all-detections-to-elastic:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      ELASTIC_KEY: $ {{ secrets.ELASTIC_KEY }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4 #docs: github.com/actions/setup-python
        with:
          python-version: '3.11.4'
      # Runs a set of commands using the runners shell
      - name: Install Requests Module
        run: pip install requests

      - name: Toml To Json To API
        run: python development/toml_to_json_to_api.py

      

