# This is a basic workflow to help you get started with Actions

name: Updated Detections To Elastic

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    path:
      '**.toml'
  # Only run this when you set up a new Elastic Version
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  updated-detections-to-elastic:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - uses: actions/setup-python@v4 #docs: github.com/actions/setup-python
        with:
          python-version: '3.11.4'

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        #object = steps.changed-files.outputs.all_changed_files

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

      - name: Install Requests Module
        run: pip install requests

      - name: Run Updated Alert Script - to Elastic
        env: 
          ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: python development/elastic-api/update_rule.py

      

